# Generated by Django 6.1.1 on 2026-09-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('first_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('n_rows', models.PositiveIntegerField(default=0)),
                ('prices_path', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_hash', models.CharField(max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('train_start', models.DateField()),
                ('train_end', models.DateField()),
                ('test_start', models.DateField()),
                ('test_end', models.DateField()),
                ('n_train', models.PositiveIntegerField()),
                ('n_test', models.PositiveIntegerField()),
                ('baseline', models.JSONField(default=dict, help_text='Always-up classifier metrics')),
                ('predictions_path', models.CharField(max_length=500)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='dashboard.ticker')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('best_params', models.JSONField(default=dict)),
                ('cv_scores', models.JSONField(default=dict, help_text='{metric: [fold scores]}')),
                ('cv_accuracy_mean', models.FloatField()),
                ('cv_accuracy_std', models.FloatField()),
                ('cv_roc_auc_mean', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1', models.FloatField()),
                ('roc_auc', models.FloatField()),
                ('confusion', models.JSONField(default=list)),
                ('roc', models.JSONField(default=dict, help_text='{fpr, tpr, auc}')),
                ('importance', models.JSONField(default=dict, help_text='{feature: [mean, std]}')),
                ('model_path', models.CharField(max_length=500)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.trainingrun')),
            ],
            options={
                'ordering': ['run', 'id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'model_name'), name='unique_model_per_run')],
            },
        ),
    ]
