# Generated by Django 6.1.1 on 2026-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresult',
            name='walk_forward',
            field=models.JSONField(blank=True, default=dict, help_text='Walk-forward test {metrics, confusion}; empty for runs trained without it'),
        ),
    ]
