# Generated by Django 6.1.1 on 2026-09-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_modelresult_walk_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='heuristic',
            field=models.JSONField(blank=True, default=dict, help_text='No-model rule metrics (volatility target only)'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='target',
            field=models.CharField(db_index=True, default='direction', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingrun',
            name='baseline',
            field=models.JSONField(default=dict, help_text='Always-positive classifier metrics'),
        ),
    ]
