# -*- coding: utf-8 -*-
"""Machine Learning Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYo2X9Nk2MlDH8ee-zuO6rIMJQPVOdkc

BARCLAYS

Import and Initialize
"""

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import numpy as np                        #for numerical computation
import pandas as pd                       #for dataframe usage
import matplotlib.pyplot as plt           #to visualise data
from sklearn.preprocessing import StandardScaler #to normalize data
from sklearn.model_selection import train_test_split #to prepare data for ML methods
import yfinance as yf

pd.options.mode.chained_assignment = None
# Don't show the warning when writing in a copy slice, not the original data.

"""Obtain historical data on the company’s daily stock prices from 01/2000 – 12/2022 from Yahoo Finance or other platforms/websites. If the data is not available in 2000 or 2022, use the maximum available length of the period during 2000 – 2022."""

dataset = yf.download("BARC.L", start="2000-01-01", end="2022-12-31")

dataset

"""Exploratory Data Analysis"""

plt.plot(dataset['Close'])

# Add title and axis labels
plt.title('Stock Prices')
#plt.xlabel('Date')
plt.ylabel('Price')

# Display the plot
plt.show()

"""Here we see a sudden dip in stock price in 2022 which needs to be explored further."""

fig, ax = plt.subplots()
ax.boxplot(dataset['Close'], vert=False)  # vert=False for a horizontal box plot
ax.set_title('Box Plot of Stock Close Prices')
ax.set_xlabel('Close Price')

plt.show()

# Prepare data
close_prices = dataset['Close']

# Assuming close_prices is a pandas Series containing the stock close prices
Q1 = close_prices.quantile(0.25)
Q2 = close_prices.quantile(0.5)
Q3 = close_prices.quantile(0.75)
Q4 = close_prices.quantile(1)

IQR_lower = Q2 - Q1
IQR_upper = Q4 - Q3

lower_bound = max(Q1 - 2 * IQR_lower, 0)
upper_bound = Q3 + 2 * IQR_upper

outliers = close_prices[(close_prices < lower_bound) | (close_prices > upper_bound)]
print("Outliers:\n", outliers)

"""Replacing the outlier with the previous day's close price"""

previous_close_price = dataset.loc['2022-06-13', 'Close']
dataset.loc['2022-06-14', 'Close'] = previous_close_price
print(previous_close_price)

"""### Feature Engineering

Generate some features that measure the characteristics of stock prices such
as rolling averages and rolling standard deviations.
"""

#Preparing the data
dataset = dataset.dropna() #Drop NULL Values
dataset = dataset[['Open', 'High', 'Low', 'Close','Volume']]

dataset['H-L'] = dataset['High'] - dataset['Low']     #high minus low
dataset['O-C'] = dataset['Close'] - dataset['Open']   #open minus close
dataset['3day MA'] = dataset['Close'].shift(1).rolling(window = 3).mean() #Using Shift(1) will display the mean of 1,2,3rd entry against 4th entry.
dataset['10day MA'] = dataset['Close'].shift(1).rolling(window = 10).mean()
dataset['30day MA'] = dataset['Close'].shift(1).rolling(window = 30).mean()  #shift down by 1 so we can assess the price rise
dataset['Std_dev']= dataset['Close'].rolling(5).std()

dataset['Price_Rise'] = np.where(dataset['Close'].shift(-1) > dataset['Close'], 1, 0) #Creating binary column for target.

dataset = dataset.dropna()
print(dataset.head())

"""Including EMA as our feature

Plotting EMA
##### Exponential moving average (EMA) is another type of moving average that can be used to analyze stock prices. Unlike a simple moving average (SMA), which equally weights all observations in the window, the EMA applies more weight to recent data points, making it more sensitive to recent price movements. This can be helpful in capturing short-term trends and potentially provide a better signal for predicting stock price movements.
"""

dataset['3day EMA'] = dataset['Close'].ewm(span=3, adjust=False).mean()
dataset['10day EMA'] = dataset['Close'].ewm(span=10, adjust=False).mean()
dataset['30day EMA'] = dataset['Close'].ewm(span=30, adjust=False).mean()

new_order = ['Open', 'High', 'Low', 'Close', 'Volume','H-L','O-C','3day MA','10day MA','30day MA','Std_dev' ,'3day EMA','10day EMA','30day EMA','Price_Rise']
dataset = dataset.reindex(columns=new_order)
dataset

"""Box Plots of Close Prices grouped by Price Rise"""

import seaborn as sns

sns.boxplot(x='Price_Rise', y='Close', data=dataset)
plt.title('Box Plots of Close Prices Grouped by Price Rise')
plt.xlabel('Price Rise (1 = Yes, 0 = No)')
plt.ylabel('Close Price')
plt.show()

"""Using box plots with more than one feature"""

def plot_grouped_boxplots(dataset, features, groupby_col):
    for feature in features:
        sns.boxplot(x=groupby_col, y=feature, data=dataset)
        plt.title(f'Box Plots of {feature} Grouped by {groupby_col}')
        plt.xlabel(f'{groupby_col} (1 = Yes, 0 = No)')
        plt.ylabel(feature)
        plt.show()
features = ['Volume','H-L','O-C','3day MA','10day MA','30day MA','Std_dev','3day EMA','10day EMA','30day EMA' ]
plot_grouped_boxplots(dataset, features, 'Price_Rise')

"""Plotting SMA"""

# Slice the data to use only a subsection
start_date = '2020-01-01'
end_date = '2021-04-01'
stock_data = dataset.loc[start_date:end_date]

fig, ax = plt.subplots(figsize=(8, 6))

ax.plot(stock_data.index, stock_data['Close'], label='Close Price', alpha=0.7)
ax.plot(stock_data.index, stock_data['3day MA'], label='3 day SMA', alpha=0.7)
ax.plot(stock_data.index, stock_data['10day MA'], label='10 day SMA', alpha=0.7)
ax.plot(stock_data.index, stock_data['30day MA'], label='30 day SMA', alpha=0.7)

ax.set_ylabel('Price')
ax.set_title('Close Price vs. Simple Moving Averages')
ax.legend()

plt.show()

"""We see the higher sensitivity of 3day SMA to Close Prices as compared to 30day SMA. This is also intuitive.

Plotting EMA
"""

# Slice the data to use only a subsection
start_date = '2020-01-01'
end_date = '2021-04-01'

fig, ax = plt.subplots(figsize=(8, 6))

ax.plot(stock_data.index, stock_data['Close'], label='Close Price', alpha=0.7)
ax.plot(stock_data.index, stock_data['3day EMA'], label='3 day EMA', alpha=0.7)
ax.plot(stock_data.index, stock_data['10day EMA'], label='10 day EMA', alpha=0.7)
ax.plot(stock_data.index, stock_data['30day EMA'], label='30 day EMA', alpha=0.7)
ax.plot(stock_data.index, stock_data['3day MA'], label='3 day SMA', alpha=0.7)
ax.plot(stock_data.index, stock_data['10day MA'], label='10 day SMA', alpha=0.7)
ax.plot(stock_data.index, stock_data['30day MA'], label='30 day SMA', alpha=0.7)

ax.set_ylabel('Price')
ax.set_title('Close Price vs. Exponential Moving Averages')
ax.legend()

plt.show()

start_date = '2020-01-01'
end_date = '2021-04-01'
stock_data = dataset.loc[start_date:end_date]

stock_data['Close_pct_change'] = stock_data['Close'].pct_change()
stock_data['3_day_MA_pct_change'] = stock_data['3day MA'].pct_change()
stock_data['10_day_MA_pct_change'] = stock_data['10day MA'].pct_change()
stock_data['30_day_MA_pct_change'] = stock_data['30day MA'].pct_change()

stock_data[['Close_pct_change', '3_day_MA_pct_change', '10_day_MA_pct_change', '30_day_MA_pct_change']].plot(figsize=(10, 6))

SMA_correlations = dataset[['Close', '3day MA', '10day MA', '30day MA']].corr()
EMA_correlations = dataset[['Close', '3day EMA', '10day EMA', '30day EMA']].corr()
print(SMA_correlations)
print(EMA_correlations)

# Slice the data to use only a subsection
start_date = '2020-01-01'
end_date = '2021-04-01'
stock_data = dataset.loc[start_date:end_date]


fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(stock_data.index, stock_data['Close'], label='Close Price')
ax.plot(stock_data.index, stock_data['10day EMA'], label='10day EMA')
ax.plot(stock_data.index, stock_data['30day EMA'], label='30day EMA')

# Find crossover points
crossovers = (stock_data['10day EMA'].shift() < stock_data['30day EMA'].shift()) & (stock_data['10day EMA'] > stock_data['30day EMA'])
crossunder = (stock_data['10day EMA'].shift() > stock_data['30day EMA'].shift()) & (stock_data['10day EMA'] < stock_data['30day EMA'])

ax.scatter(stock_data[crossovers].index, stock_data['10day EMA'][crossovers], marker='^', color='g', label='Crossover')
ax.scatter(stock_data[crossunder].index, stock_data['10day EMA'][crossunder], marker='v', color='r', label='Crossunder')

plt.legend()

"""Including crossovers as a binary signal in our model
##### Creating a binary variable that indicates whether the short-term moving average is greater than the long-term moving average:
The EMA_crossover feature contains 0s where the 10-day EMA is greater than the 30-day EMA, representing a buy signal and 1s otherwise.

"""

dataset['EMA_diff'] = dataset['10day EMA'] - dataset['30day EMA']
dataset['EMA_crossover'] = (dataset['EMA_diff'] < 0).astype(int)
dataset

"""### RSI
- This indicator measures the strength of a stock's price action relative to its previous price action. The RSI ranges from 0 to 100, with readings above 70 indicating overbought conditions and readings below 30 indicating oversold conditions.
"""

# Calculate RSI
def calculate_rsi(data, n=14):
    delta = data['Close'].diff()
    up = delta.where(delta > 0, 0)
    down = -delta.where(delta < 0, 0)
    ema_up = up.ewm(com=n - 1, min_periods=n).mean()
    ema_down = down.ewm(com=n - 1, min_periods=n).mean()
    rs = ema_up / ema_down
    return pd.Series(100 - (100 / (1 + rs)))

dataset['RSI'] = calculate_rsi(dataset)
dataset = dataset.dropna()

new_order = ['Open', 'High', 'Low', 'Close', 'Volume','H-L','O-C','3day MA','10day MA','30day MA','Std_dev' ,'3day EMA','10day EMA','30day EMA','EMA_crossover','RSI','EMA_diff','Price_Rise']
dataset = dataset.reindex(columns=new_order)
#dataset

"""Plotting RSI"""

# Slice the data to use only a subsection
start_date = '2020-01-01'
end_date = '2021-04-01'
stock_data = dataset.loc[start_date:end_date]

# Create the plot
fig, ax1 = plt.subplots()

# Plot the stock price on the primary axis
ax1.plot(stock_data['Close'], color='blue', alpha=0.7)

ax1.set_ylabel('Closing Price', color='blue')

# Create a secondary axis for RSI
ax2 = ax1.twinx()
ax2.plot(stock_data['RSI'], color='orange', alpha=0.7)
ax2.set_ylabel('RSI', color='orange')

# Add gridlines
plt.grid(linestyle='--', linewidth=0.5, color='gray', alpha=0.7)

# Add a title
plt.title('Stock Price and RSI')

# Show the plot
plt.show()

"""### Bollinger Bands
- This indicator uses a moving average and two standard deviations to create a channel around the stock price. The width of the channel changes based on volatility, and the price is expected to stay within the channel. If the price moves outside the channel, it can indicate a trend reversal.


"""

# Calculate the 20-day moving average
dataset['MA20'] = dataset['Close'].rolling(window=20).mean()

# Calculate the upper and lower bands based on 2 standard deviations from the moving average
dataset['Upper'] = dataset['MA20'] + 2 * dataset['Close'].rolling(window=20).std()
dataset['Lower'] = dataset['MA20'] - 2 * dataset['Close'].rolling(window=20).std()
dataset['Middle'] = dataset['Close'].rolling(window=20).mean()


# Calculate distance between price and bands as a percentage of the width of the bands
dataset['band_distance'] = (dataset['Close'] - dataset['Middle']) / (dataset['Upper'] - dataset['Lower'])


new_order = ['Open', 'High', 'Low', 'Close', 'Volume','H-L','O-C','3day MA','10day MA','30day MA','Std_dev' ,'3day EMA','10day EMA','30day EMA','EMA_crossover','RSI','band_distance','EMA_diff','MA20','Upper','Lower','Middle','Price_Rise']
dataset = dataset.reindex(columns=new_order)

"""Plotting Bollinger Bands"""

dataset = dataset.dropna()

# Slice the data to use only a subsection
start_date = '2020-01-01'
end_date = '2021-04-01'
stock_data = dataset.loc[start_date:end_date]

# Plot the stock price and Bollinger Bands
plt.figure(figsize=(12,6))
plt.plot(stock_data['Close'], label='Close Price')
plt.plot(stock_data['Upper'], label='Upper Band')
plt.plot(stock_data['Lower'], label='Lower Band')
plt.title('Bollinger Bands for Barclays')
plt.xlabel('Date')
plt.ylabel('Price')
plt.grid(True)
plt.legend()
plt.show()

"""Including MACD
- Calculate the difference between short-term and long-term moving averages, which can indicate momentum and trend changes.
"""

def macd(data, short_window, long_window):
    short_ma = dataset['Close'].ewm(span=short_window).mean()
    long_ma = dataset['Close'].ewm(span=long_window).mean()
    return short_ma - long_ma

dataset['MACD'] = macd(dataset, 12, 26)

new_order = ['Open', 'High', 'Low', 'Close', 'Volume','H-L','O-C','3day MA','10day MA','30day MA','Std_dev' ,'3day EMA','10day EMA','30day EMA','EMA_crossover','RSI','band_distance','MACD','EMA_diff','MA20','Upper','Lower','Middle','Price_Rise']
dataset = dataset.reindex(columns=new_order)
dataset = dataset.dropna()
dataset

"""Plotting boxplots for Bollinger bands, RSI and MACD, grouped by price rise"""

def plot_grouped_boxplots(dataset, features, groupby_col):
    for feature in features:
        sns.boxplot(x=groupby_col, y=feature, data=dataset)
        plt.title(f'Box Plots of {feature} Grouped by {groupby_col}')
        plt.xlabel(f'{groupby_col} (1 = Yes, 0 = No)')
        plt.ylabel(feature)
        plt.show()

features = ['RSI','band_distance','MACD']

plot_grouped_boxplots(dataset, features, 'Price_Rise')

"""The distribution by price rise is largely the same

### Univariate Analysis on features
"""

# Select the relevant columns
features = ['Close', 'Volume', 'O-C', 'H-L', '3day MA', '10day MA', '30day MA', '3day EMA', '10day EMA', '30day EMA','Std_dev', 'RSI', 'MACD','band_distance']

from scipy.stats import skew, kurtosis

def plot_features(dataset, features):
    for feature in features:
        # Calculate mean, standard deviation, skewness, and kurtosis
        mean = dataset[feature].mean()
        std_dev = dataset[feature].std()
        skewness = skew(dataset[feature])
        kurt = kurtosis(dataset[feature])

        # Plot histogram
        plt.figure()
        sns.histplot(dataset[feature], kde=True, color='blue', bins=30)
        plt.axvline(mean, color='red', linestyle='--', label=f'Mean: {mean:.2f}')
        plt.axvline(mean - std_dev, color='green', linestyle='--', label=f'SD: {std_dev:.2f}')
        plt.axvline(mean + std_dev, color='green', linestyle='--')

        # Add legend and labels
        plt.legend()
        plt.xlabel(feature)
        plt.ylabel('Frequency')
        plt.title(f'Histogram of {feature} with Mean, SD, Skewness ({skewness:.2f}), and Kurtosis ({kurt:.2f})')
        plt.show()

plot_features(dataset, features)

"""Adding all features to dataset"""

#specifying x and y
X = dataset.iloc[:, 4:-6]
y = dataset.iloc[:, -1]
X

#splitting x and y into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, shuffle=False) #since split is not random so shuffle = false. This is so we are later able to compare with market data
print(X_test)

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling

"""### Multivariate Analysis"""

import seaborn as sns

# Slice the data to use only a subsection
start_date = '2020-01-01'
end_date = '2021-04-01'
stock_data = dataset.loc[start_date:end_date]

# Select the features to be included in the pairwise scatter plot matrix
features = ['Volume', 'O-C', 'H-L', '3day MA', '10day MA', '30day MA', '3day EMA', '10day EMA', '30day EMA','Std_dev', 'RSI', 'band_distance','MACD','Price_Rise']

# Create a pairwise scatter plot matrix of the selected features
sns.pairplot(data=stock_data[features], diag_kind='kde', hue = 'Price_Rise', height=1.5,corner=True)

# Calculate the correlation matrix
corr_matrix = dataset[features].corr()

# Create a mask to show only the lower triangle of the matrix
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

# Create a heatmap to visualize the correlation matrix
plt.figure(figsize=(12, 9))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='coolwarm', mask=mask, linewidths=0.5)
plt.title("Correlation Matrix")
plt.show()

"""Using Linear Regression as part of Multivariate Analysis"""

dataset=dataset.dropna()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

#specifying x and y
feature_columns = ['O-C', 'H-L', '3day MA', '10day MA', '30day MA', '3day EMA', '10day EMA', '30day EMA','EMA_crossover','Std_dev', 'RSI', 'band_distance','MACD']
X = dataset[feature_columns]
y = dataset.iloc[:, -1]

#splitting x and y into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, shuffle=False) #since split is not random so shuffle = false. This is so we are later able to compare with market data

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling

# Create and fit the model
model = LinearRegression()
model.fit(X_train, Y_train)

# Make predictions and evaluate the model
Y_pred = model.predict(X_test)
mse = mean_squared_error(Y_test, Y_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(Y_test, Y_pred)
print("R-squared:", r2)

"""### Principal Component Analysis
- PCA can help reduce the dimensionality of the input features and remove noise, potentially improving the performance of the model. By using PCA, we can transform the original features into a smaller set of principal components, which can then be used as input for the machine learning model. It creates new features (principal components) as linear combinations of the original features.
"""

from sklearn.decomposition import PCA
import seaborn as sns

# Standardize the entire dataset
X_std = sc.fit_transform(X)

# Apply PCA
pca = PCA(n_components=8)
X_pca = pca.fit_transform(X_std)

print("Explained Variance Ratio:", (pca.explained_variance_ratio_)*100,'%')

components_df = pd.DataFrame(pca.components_, columns=feature_columns)

plt.figure(figsize=(12, 6))
sns.heatmap(components_df, cmap='coolwarm', annot=True, vmin=-1, vmax=1)
plt.xlabel('Original Features')
plt.ylabel('Principal Components')
plt.title('PCA Components vs Original Features')
plt.show()

"""The heatmap helps us understand the significance of each feature in the principal components.

Assessing the impact of PCA on our model with Linear Regression
"""

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling

# Without PCA
model = LinearRegression()
scores = cross_val_score(model, X, y, cv=5, scoring='r2')
print("Without PCA - R-squared (mean):", np.mean(scores))

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling

# With PCA
pca = PCA(n_components=8)
model = LinearRegression()
pipeline = Pipeline(steps=[('pca', pca), ('model', model)])
scores = cross_val_score(pipeline, X, y, cv=5, scoring='r2')
print("With PCA - R-squared (mean):", np.mean(scores))

"""## Time Series Analysis
Time series analysis is particularly important for stock price prediction, as it takes into account the temporal dependencies in the data.

### AutoRegression
##### Autoregression models the relationship between an observation and a number of lagged observations (previous time steps). The AR model can be useful for predicting the next value in the time series based on the values at previous time steps.
"""

from statsmodels.tsa.ar_model import AutoReg

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Fit Autoregression model
lag = 5
model = AutoReg(Y_train, lags=lag)
model_fit = model.fit()

# Forecast
forecast = model_fit.predict(start=len(Y_train), end=len(Y_train) + len(Y_test) - 1)

# Evaluate the model
mse = mean_squared_error(Y_test, forecast)
print("Mean Squared Error:", mse)
r2 = r2_score(Y_test, Y_pred)
print("R-squared:", r2)

"""A lower MSE generally indicates better performance. However, the absolute value of MSE is scale-dependant and hence not directly comparable across datasets. R-squared : R-squared, the coefficient of determination, measures the proportion of the variance in the dependent variable that is predictable from the independent variables. It ranges from 0 to 1, with values closer to 1 indicating better performance.

### Autocorrelation and Partial Auto-correlation Analysis
"""

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Autocorrelation plot
plot_acf(dataset['Close'], lags=30)
plt.show()

"""- The autocorrelation plot  measures the linear relationship between the value at time t and the values at previous time steps (lags). A significant autocorrelation at a specific lag indicates that there is some dependency between the current value and the value at that lag, suggesting trends or seasonality in the data.
- Such strong autocorrelation in the data may indicate that the time series is non-stationary and so have time varying  mean and variance, which can make modeling and forecasting challenging. In such cases, we could look at transforming data such as using logarithmic returns or stcok price differencing.
- However, our tree-based methods (e.g., Random Forest and Gradient Boosting) can model non-linear relationships and do not require the input data to be stationary, so they would be less sensitive to data transformations.

Time Series Decomposition

We now try to assess if there is an underlying structure of the stock price data. This method will break down the time series into its constituent components of trend, seasonality, and residuals.
"""

from statsmodels.tsa.seasonal import seasonal_decompose
# Time series decomposition
result = seasonal_decompose(dataset['Close'], model='additive', period=30)

# Forward fill missing values
dataset = dataset.fillna(method='ffill')

# Plot decomposition
result.plot()
plt.show()

"""There is a clear underlying trend in the stock price data. The seasonality component does not appear to be strong. There are some irregular fluctuations in the stock price data that are not captured by the trend and seasonality components, especially around the period of global financial crisis.

Using PCA and Recursive Feature Elimination
"""

# Recursive Feature Elimination
from sklearn.feature_selection import RFE

model = LinearRegression()

# Assuming X_train and X_test are numpy arrays
X_train = pd.DataFrame(X_train, columns=X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)

# Initialize and fit RFE
rfe = RFE(model, n_features_to_select=5)
rfe.fit(X_train, Y_train)

# Display selected features
selected_features = X_train.columns[rfe.support_]
print("Selected Features:", selected_features)

# Standardize the selected features
sc = StandardScaler()
X_train_rfe = sc.fit_transform(X_train.loc[:, rfe.support_])
X_test_rfe = sc.transform(X_test.loc[:, rfe.support_])

# With PCA
pca = PCA(n_components=5)
X_rfe_pca_train = pca.fit_transform(X_train_rfe)

# Fit and evaluate the model's performance
model.fit(X_rfe_pca_train, Y_train)
scores = cross_val_score(model, X_rfe_pca_train, Y_train, cv=5, scoring='r2')
print("With PCA and RFE - R-squared (mean):", np.mean(scores))

# Make predictions and evaluate the model
X_rfe_pca_test = pca.transform(X_test_rfe)
y_pred = model.predict(X_rfe_pca_test)
mse = mean_squared_error(Y_test, y_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(Y_test, y_pred)
print("R-squared:", r2)

"""The combination of PCA and RFE with a linear regression model does not provide a good fit for the data. So we will now explore other non-linear models"""

dataset = dataset.dropna()
#specifying x and y
X = dataset.iloc[:, 4:-5]
y = dataset.iloc[:, -1]

#splitting x and y into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, shuffle=False) #since split is not random so shuffle = false. This is so we are later able to compare with market data

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling
Y_train

"""We now use the following machine learning classification methods to predict the price rise: Support vector machines, Random Forest, Bagging (with K-nearest
neighbor), and Gradient Boosting.
For each method, we run a RFE and cross-validation to calculate the mean and standard deviation of the accuracy.

SVM with linear kernel
"""

from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
hypothesis_svm = SVC(kernel='linear', random_state=101)


scores = cross_val_score(hypothesis_svm, X_train, Y_train, cv=5, scoring='accuracy') #cv = no. of folds in cv.
print ("SVC with linear kernel -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores), np.std(scores)))

mse = mean_squared_error(Y_test, Y_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(Y_test, Y_pred)
print("R-squared:", r2)

"""Running RFE"""

# Run RFE with the SVM model
rfe = RFE(estimator=SVC(kernel='linear'), n_features_to_select=5)
rfe.fit(X_train, Y_train)

# Train and test the SVM model with the features selected by RFE
X_train_rfe = rfe.transform(X_train)
X_test_rfe = rfe.transform(X_test)

hypothesis_svm_rfe = SVC(kernel='linear', random_state=101)

scores_rfe = cross_val_score(hypothesis_svm_rfe, X_train_rfe, Y_train, cv=5, scoring='accuracy')
print("SVC with linear kernel (with RFE) -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores_rfe), np.std(scores_rfe)))

hypothesis_svm_rfe.fit(X_train_rfe, Y_train)
y_pred_rfe = hypothesis_svm_rfe.predict(X_test_rfe)

mse_rfe = mean_squared_error(Y_test, y_pred_rfe)
print("Mean Squared Error (with RFE):", mse_rfe)
r2_rfe = r2_score(Y_test, y_pred_rfe)
print("R-squared (with RFE):", r2_rfe)

"""SVC with rbf"""

X = dataset.iloc[:, 4:-5]
y = dataset.iloc[:, -1]

#splitting x and y into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, shuffle=False) #since split is not random so shuffle = false. This is so we are later able to compare with market data

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling
Y_train

from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
hypothesis_svm = SVC(kernel='rbf', random_state=101)

scores = cross_val_score(hypothesis_svm, X_train, Y_train, cv=5, scoring='accuracy') #cv = no. of folds in cv.
print ("SVC with rbf kernel -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores), np.std(scores)))

mse = mean_squared_error(Y_test, Y_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(Y_test, Y_pred)
print("R-squared:", r2)

"""Using Univariate Feature Selection with SVM_rbf
##### This method assesses the relationship between individual features and the target variable without considering interactions between features.
"""

from sklearn.feature_selection import SelectKBest, f_classif

dataset = dataset.dropna()
X = dataset.iloc[:, 4:-5]
y = dataset.iloc[:, -1]

y = y.astype(int)
#splitting x and y into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, shuffle=False) #since split is not random so shuffle = false. This is so we are later able to compare with market data

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling

# Create the feature selector
k_best_selector = SelectKBest(f_classif, k=5)

# Fit the selector on the training data
k_best_selector.fit(X_train, Y_train)

# Transform the training and test datasets
X_train_kbest = k_best_selector.transform(X_train)
X_test_kbest = k_best_selector.transform(X_test)

hypothesis_svm_rbf = SVC(kernel='rbf', random_state=101)

hypothesis_svm_rbf.fit(X_train_kbest, Y_train)
y_pred_rbf = hypothesis_svm_rbf.predict(X_test_kbest)

scores_rbf = cross_val_score(hypothesis_svm_rfe, X_train_kbest, Y_train, cv=5, scoring='accuracy')
print("SVC with rbf kernel -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores_rfe), np.std(scores_rfe)))

mse_rbf = mean_squared_error(Y_test, y_pred_rbf)
print("Mean Squared Error :", mse_rbf)
r2_rbf = r2_score(Y_test, y_pred_rbf)
print("R-squared :", r2_rbf)

"""Using Permutation Importance"""

from sklearn.inspection import permutation_importance

X = dataset.iloc[:, 4:-5]
y = dataset.iloc[:, -1]
y = y.astype(int)

#splitting x and y into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, shuffle=False) #since split is not random so shuffle = false. This is so we are later able to compare with market data

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling

# Train our model
hypothesis_svm = SVC(kernel='rbf', random_state=101)

hypothesis_svm.fit(X_train, Y_train)

# Compute permutation importances
result = permutation_importance(hypothesis_svm, X_test, Y_test, n_repeats=10, random_state=0)

# Get the indices of the most important features (e.g., the top 5 features)
sorted_idx = result.importances_mean.argsort()
top_feature_indices = sorted_idx[-5:]

# Use these indices to select the top features from the dataset
X_train_top_features = X_train[:, top_feature_indices]
X_test_top_features = X_test[:, top_feature_indices]

# Train our model
hypothesis_svm = SVC(kernel='rbf', random_state=101)

hypothesis_svm.fit(X_train_top_features, Y_train)

scores = cross_val_score(hypothesis_svm, X_train_top_features, Y_train, cv=5, scoring='accuracy')
print("SVC with rbf kernel -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores), np.std(scores)))

hypothesis_svm.fit(X_train_top_features, Y_train)
y_pred = hypothesis_svm.predict(X_test_kbest)

mse = mean_squared_error(Y_test, y_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(Y_test, y_pred)
print("R-squared (with RFE):", r2)

"""Classification Report"""

hypothesis_svm.fit(X_train, Y_train)
Y_pred = hypothesis_svm.predict(X_test)
from sklearn.metrics import classification_report
print (classification_report(Y_test, Y_pred))

"""Evaluation"""

Y_pred = (Y_pred > 0.5)
dataset['Y_pred'] = np.NaN
dataset.iloc[(len(dataset) - len(Y_pred)):,-1] = Y_pred
trade_dataset = dataset.dropna()
comparison_dataset = dataset.dropna()
trade_dataset['Tomorrows Returns'] = 0.
trade_dataset['Tomorrows Returns'] = np.log(trade_dataset['Close']/trade_dataset['Close'].shift(1))
trade_dataset['Tomorrows Returns'] = trade_dataset['Tomorrows Returns'].shift(-1)

trade_dataset['Strategy Returns'] = 0.
trade_dataset['Strategy Returns'] = np.where(trade_dataset['Y_pred'] == True, trade_dataset['Tomorrows Returns'], - trade_dataset['Tomorrows Returns'])

trade_dataset['Cumulative Market Returns'] = np.cumsum(trade_dataset['Tomorrows Returns'])
trade_dataset['Support Vector Machine Returns'] = np.cumsum(trade_dataset['Strategy Returns'])

comparison_dataset['SVM'] = np.cumsum(trade_dataset['Strategy Returns'])


import matplotlib.pyplot as plt
trade_dataset = trade_dataset.dropna()
plt.figure(figsize=(10,5))
plt.plot(trade_dataset['Cumulative Market Returns'], color='r', label='Market Returns')
plt.plot(trade_dataset['Support Vector Machine Returns'], color='g', label='Support Vector Machine')
plt.legend()
plt.show()

dataset = dataset.dropna()

"""Linear SVC"""

from sklearn.svm import LinearSVC
from sklearn.model_selection import cross_val_score
hypothesis_lsvc = LinearSVC(max_iter = 10000)
scores = cross_val_score(hypothesis_lsvc, X_train, Y_train, cv=5, scoring='accuracy')
print ("LinearSVC -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores), np.std(scores)))

"""Using RFE"""

from sklearn.svm import LinearSVC
from sklearn.feature_selection import RFE

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling

hypothesis_lsvc = LinearSVC(max_iter=10000)

rfe = RFE(estimator=hypothesis_lsvc, n_features_to_select=5)
rfe.fit(X_train, Y_train)

X_train_rfe = rfe.transform(X_train)
X_test_rfe = rfe.transform(X_test)

hypothesis_lsvc_rfe = LinearSVC(max_iter=10000)
hypothesis_lsvc_rfe.fit(X_train_rfe, Y_train)
y_pred_rfe = hypothesis_lsvc_rfe.predict(X_test_rfe)
scores_rfe = cross_val_score(hypothesis_lsvc_rfe, X_train_rfe, Y_train, cv=5, scoring='accuracy')
print("LinearSVC with RFE -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores_rfe), np.std(scores_rfe)))

mse_rfe = mean_squared_error(Y_test, y_pred_rfe)
print("Mean Squared Error (with RFE):", mse_rfe)
r2_rfe = r2_score(Y_test, y_pred_rfe)
print("R-squared (with RFE):", r2_rfe)

"""Classification Report"""

hypothesis_lsvc.fit(X_train, Y_train)
Y_pred = hypothesis_lsvc.predict(X_test)
from sklearn.metrics import classification_report
print (classification_report(Y_test, Y_pred))

"""Evaluation"""

Y_pred = (Y_pred > 0.5)
dataset['Y_pred'] = np.NaN
dataset.iloc[(len(dataset) - len(Y_pred)):,-1] = Y_pred
trade_dataset = dataset.dropna()
trade_dataset['Tomorrows Returns'] = 0.
trade_dataset['Tomorrows Returns'] = np.log(trade_dataset['Close']/trade_dataset['Close'].shift(1))
trade_dataset['Tomorrows Returns'] = trade_dataset['Tomorrows Returns'].shift(-1)

trade_dataset['Strategy Returns'] = 0.
trade_dataset['Strategy Returns'] = np.where(trade_dataset['Y_pred'] == True, trade_dataset['Tomorrows Returns'], - trade_dataset['Tomorrows Returns'])

trade_dataset['Cumulative Market Returns'] = np.cumsum(trade_dataset['Tomorrows Returns'])
trade_dataset['Cumulative Strategy Returns'] = np.cumsum(trade_dataset['Strategy Returns'])

comparison_dataset['Linear SVC'] = np.cumsum(trade_dataset['Strategy Returns'])

import matplotlib.pyplot as plt
trade_dataset = trade_dataset.dropna()
plt.figure(figsize=(10,5))
plt.plot(trade_dataset['Cumulative Market Returns'], color='r', label='Market Returns')
plt.plot(trade_dataset['Cumulative Strategy Returns'], color='g', label='Linear SVC')
plt.legend()
plt.show()

"""Random Forest"""

from sklearn.ensemble import RandomForestClassifier

sc = StandardScaler() #normalize data (x-mean)/sd for ML
X_train = sc.fit_transform(X_train) #fit to data then transform it. Fit->compute mean and std to be used for later scaling
X_test = sc.transform(X_test) #perform standardization by centering and scaling

hypothesis_rf = RandomForestClassifier(random_state=101)
scores = cross_val_score(hypothesis_rf, X_train, Y_train,
                         cv=3, scoring='accuracy')
print ("RandomForestClassifier -> cross validation accuracy: mean = %0.3f \
std = %0.3f" % (np.mean(scores), np.std(scores)))

"""Random Forests using PCA and RFE"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.feature_selection import RFE

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# With PCA
pca = PCA(n_components=5)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# RFE with RandomForestClassifier
rfe = RFE(estimator=RandomForestClassifier(random_state=101), n_features_to_select=5)
rfe.fit(X_train_pca, Y_train)

X_train_pca_rfe = rfe.transform(X_train_pca)
X_test_pca_rfe = rfe.transform(X_test_pca)

hypothesis_rf_pca_rfe = RandomForestClassifier(random_state=101)
scores_pca_rfe = cross_val_score(hypothesis_rf_pca_rfe, X_train_pca_rfe, Y_train, cv=3, scoring='accuracy')
print("RandomForestClassifier with PCA and RFE -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores_pca_rfe), np.std(scores_pca_rfe)))

# Fit the model and make predictions
hypothesis_rf_pca_rfe.fit(X_train_pca_rfe, Y_train)
y_pred_pca_rfe = hypothesis_rf_pca_rfe.predict(X_test_pca_rfe)

"""Classification Report"""

hypothesis_rf.fit(X_train, Y_train)
Y_pred = hypothesis_rf.predict(X_test)
from sklearn.metrics import classification_report
print (classification_report(Y_test, Y_pred))

"""Evaluation"""

Y_pred = (Y_pred > 0.5)
dataset['Y_pred'] = np.NaN
dataset.iloc[(len(dataset) - len(Y_pred)):,-1] = Y_pred
trade_dataset = dataset.dropna()
trade_dataset['Tomorrows Returns'] = 0.
trade_dataset['Tomorrows Returns'] = np.log(trade_dataset['Close']/trade_dataset['Close'].shift(1))
trade_dataset['Tomorrows Returns'] = trade_dataset['Tomorrows Returns'].shift(-1)

trade_dataset['Strategy Returns'] = 0.
trade_dataset['Strategy Returns'] = np.where(trade_dataset['Y_pred'] == True, trade_dataset['Tomorrows Returns'], - trade_dataset['Tomorrows Returns'])

trade_dataset['Cumulative Market Returns'] = np.cumsum(trade_dataset['Tomorrows Returns'])
trade_dataset['Cumulative Strategy Returns'] = np.cumsum(trade_dataset['Strategy Returns'])

comparison_dataset['Random Forest'] = np.cumsum(trade_dataset['Strategy Returns'])

import matplotlib.pyplot as plt
trade_dataset = trade_dataset.dropna()
plt.figure(figsize=(10,5))
plt.plot(trade_dataset['Cumulative Market Returns'], color='r', label='Market Returns')
plt.plot(trade_dataset['Cumulative Strategy Returns'], color='g', label='Random Forest')
plt.legend()
plt.show()

"""Extra Trees Classifier"""

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.decomposition import PCA
from sklearn.feature_selection import RFE

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# With PCA
pca = PCA(n_components=5)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# RFE with ExtraTreesClassifier
rfe = RFE(estimator=ExtraTreesClassifier(random_state=101), n_features_to_select=5)
rfe.fit(X_train_pca, Y_train)

X_train_pca_rfe = rfe.transform(X_train_pca)
X_test_pca_rfe = rfe.transform(X_test_pca)

hypothesis_etc_pca_rfe = ExtraTreesClassifier(random_state=101)
scores_pca_rfe = cross_val_score(hypothesis_etc_pca_rfe, X_train_pca_rfe, Y_train, cv=3, scoring='accuracy')
print("ExtraTreesClassifier with PCA and RFE -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores_pca_rfe), np.std(scores_pca_rfe)))

# Fit the model and make predictions
hypothesis_etc_pca_rfe.fit(X_train_pca_rfe, Y_train)
y_pred_pca_rfe = hypothesis_etc_pca_rfe.predict(X_test_pca_rfe)

"""Classification Report"""

hypothesis_etc_pca_rfe.fit(X_train, Y_train)
Y_pred = hypothesis_etc_pca_rfe.predict(X_test)
from sklearn.metrics import classification_report
print (classification_report(Y_test, Y_pred))

"""Evaluation"""

Y_pred = (Y_pred > 0.5)
dataset['Y_pred'] = np.NaN
dataset.iloc[(len(dataset) - len(Y_pred)):,-1] = Y_pred
trade_dataset = dataset.dropna()
trade_dataset['Tomorrows Returns'] = 0.
trade_dataset['Tomorrows Returns'] = np.log(trade_dataset['Close']/trade_dataset['Close'].shift(1))
trade_dataset['Tomorrows Returns'] = trade_dataset['Tomorrows Returns'].shift(-1)

trade_dataset['Strategy Returns'] = 0.
trade_dataset['Strategy Returns'] = np.where(trade_dataset['Y_pred'] == True, trade_dataset['Tomorrows Returns'], - trade_dataset['Tomorrows Returns'])

trade_dataset['Cumulative Market Returns'] = np.cumsum(trade_dataset['Tomorrows Returns'])
trade_dataset['Cumulative Strategy Returns'] = np.cumsum(trade_dataset['Strategy Returns'])

comparison_dataset['Extra Tree Classifier'] = np.cumsum(trade_dataset['Strategy Returns'])

import matplotlib.pyplot as plt
trade_dataset = trade_dataset.dropna()
plt.figure(figsize=(10,5))
plt.plot(trade_dataset['Cumulative Market Returns'], color='r', label='Market Returns')
plt.plot(trade_dataset['Cumulative Strategy Returns'], color='g', label='Extra Tree Classifier')
plt.legend()
plt.show()

"""Bagging (with K-nearest neighbor) using PCA

RFE is not compatible with Bagging KNeighbours Classifier.
"""

from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# With PCA
pca = PCA(n_components=5)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

hypothesis_bagging_pca = BaggingClassifier(KNeighborsClassifier())
scores_pca = cross_val_score(hypothesis_bagging_pca, X_train_pca, Y_train, cv=3, scoring='accuracy')
print("BaggingClassifier with PCA -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores_pca), np.std(scores_pca)))

"""Classification Report"""

hypothesis_bagging_pca.fit(X_train, Y_train)
Y_pred = hypothesis_bagging_pca.predict(X_test)
from sklearn.metrics import classification_report
print (classification_report(Y_test, Y_pred))

"""Evaluation"""

Y_pred = (Y_pred > 0.5)
dataset['Y_pred'] = np.NaN
dataset.iloc[(len(dataset) - len(Y_pred)):,-1] = Y_pred
trade_dataset = dataset.dropna()
trade_dataset['Tomorrows Returns'] = 0.
trade_dataset['Tomorrows Returns'] = np.log(trade_dataset['Close']/trade_dataset['Close'].shift(1))
trade_dataset['Tomorrows Returns'] = trade_dataset['Tomorrows Returns'].shift(-1)

trade_dataset['Strategy Returns'] = 0.
trade_dataset['Strategy Returns'] = np.where(trade_dataset['Y_pred'] == True, trade_dataset['Tomorrows Returns'], - trade_dataset['Tomorrows Returns'])

trade_dataset['Cumulative Market Returns'] = np.cumsum(trade_dataset['Tomorrows Returns'])
trade_dataset['Cumulative Strategy Returns'] = np.cumsum(trade_dataset['Strategy Returns'])

comparison_dataset['Bagging with KNN'] = np.cumsum(trade_dataset['Strategy Returns'])

import matplotlib.pyplot as plt
trade_dataset = trade_dataset.dropna()
plt.figure(figsize=(10,5))
plt.plot(trade_dataset['Cumulative Market Returns'], color='r', label='Market Returns')
plt.plot(trade_dataset['Cumulative Strategy Returns'], color='g', label='Bagging With KNN')
plt.legend()
plt.show()

"""Gradient Boosting"""

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import RFE
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Apply PCA
pca = PCA(n_components=5)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# Apply RFE on PCA transformed data
rfe = RFE(estimator=GradientBoostingClassifier(max_depth=100, n_estimators=300, learning_rate=0.005, subsample=0.6, random_state=101), n_features_to_select=3)
rfe.fit(X_train_pca, Y_train)

X_train_pca_rfe = rfe.transform(X_train_pca)
X_test_pca_rfe = rfe.transform(X_test_pca)

# GradientBoostingClassifier with PCA and RFE
hypothesis_gradboost_pca_rfe = GradientBoostingClassifier(max_depth=100, n_estimators=300, learning_rate=0.005, subsample=0.6, random_state=101)
scores_pca_rfe = cross_val_score(hypothesis_gradboost_pca_rfe, X_train_pca_rfe, Y_train, cv=3, scoring='accuracy')
print("GradientBoostingClassifier with PCA and RFE -> cross validation accuracy: mean = %0.3f std = %0.3f" % (np.mean(scores_pca_rfe), np.std(scores_pca_rfe)))

"""Classification Report"""

hypothesis_gradboost_pca_rfe.fit(X_train, Y_train)
Y_pred = hypothesis_gradboost_pca_rfe.predict(X_test)
from sklearn.metrics import classification_report
print (classification_report(Y_test, Y_pred))

"""For the last method, predict the price rise based on your X_test data."""

print("Y_pred: \n", Y_pred)
Y_pred = (Y_pred > 0.5)
print("Y_pred > 0.5: \n", Y_pred)

dataset['Y_pred'] = np.NaN
dataset.iloc[(len(dataset) - len(Y_pred)):,-1] = Y_pred
trade_dataset = dataset.dropna()
trade_dataset

"""Draw a plot of the confusion matrix, a ROC plot, and a plot of feature importance.

Confusion Matrix
"""

Price_rise = trade_dataset['Price_Rise'].values.tolist()
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
Predicted_rise = Y_pred.tolist()
# Create confusion matrix
cm = confusion_matrix(Price_rise, Predicted_rise)

# Plot confusion matrix
sns.heatmap(cm, annot=True, fmt = 'd', cmap='Blues')
plt.xlabel('Predicted Prise Rise')
plt.ylabel('True Prise Rise')
plt.title('Confusion Matrix')

plt.show()

"""ROC Plot"""

from sklearn.metrics import RocCurveDisplay
roc_disp = RocCurveDisplay.from_estimator(hypothesis_gradboost_pca_rfe, X_test, Y_test)

"""Feature Importance Plot"""

feature_names = np.array(dataset.columns.values[4:-7])
feature_names

# Sort the importance values and their corresponding indices
importance = hypothesis_gradboost_pca_rfe.feature_importances_
indices = np.argsort(importance)

# Create the range and plot the feature importances
range1 = range(len(importance))
plt.figure()
plt.title("Gradient Boosting importance for Principal Components")
plt.barh(range1, importance[indices])
plt.yticks(range1, [f'PC{i+1}' for i in indices])
plt.ylim([-1, len(range1)])
plt.show()

"""We plotted the feature importances for the Gradient Boosting model that has been trained on the PCA-transformed features which combines the original features into new components, which means we can't directly map the feature importances back to the original feature names. So what we see is feature importances for the principal components. For the purpose of the report, we plotted features importance on Gradient Boosting without PCA or RFE

Creating the columns of Market Returns and Strategy Returns based on your
prediction of price rise.
"""

trade_dataset['Tomorrows Returns'] = 0.
trade_dataset['Tomorrows Returns'] = np.log(trade_dataset['Close']/trade_dataset['Close'].shift(1))
trade_dataset['Tomorrows Returns'] = trade_dataset['Tomorrows Returns'].shift(-1)

trade_dataset['Strategy Returns'] = 0.
trade_dataset['Strategy Returns'] = np.where(trade_dataset['Y_pred'] == True, trade_dataset['Tomorrows Returns'], - trade_dataset['Tomorrows Returns'])

"""Creating the columns of Cumulative Market Returns and Cumulative Strategy
Returns based on your prediction of price rise.
"""

trade_dataset['Cumulative Market Returns'] = np.cumsum(trade_dataset['Tomorrows Returns'])
trade_dataset['Cumulative Strategy Returns'] = np.cumsum(trade_dataset['Strategy Returns'])
trade_dataset

comparison_dataset['Gradient Boosting'] = np.cumsum(trade_dataset['Strategy Returns'])
comparison_dataset['Cumulative Market Returns'] = np.cumsum(trade_dataset['Tomorrows Returns'])

"""### Visualizations

##### Time series plot of Market Returns and Strategy Returns
"""

import matplotlib.pyplot as plt
trade_dataset = trade_dataset.dropna()
plt.figure(figsize=(10,5))
plt.plot(trade_dataset['Cumulative Market Returns'], color='r', label='Market Returns')
plt.plot(trade_dataset['Cumulative Strategy Returns'], color='g', label='Gradient Boosting Returns')
plt.legend()
plt.show()

"""Histograms and density plots of Market Returns and Strategy Returns:¶"""

returns_dataset = trade_dataset[['Cumulative Market Returns','Cumulative Strategy Returns']]
returns_dataset

import matplotlib.pyplot as plt

plt.hist(returns_dataset['Cumulative Market Returns'], alpha=0.5, bins=30)
plt.hist(returns_dataset['Cumulative Strategy Returns'], alpha=0.5, bins=30)
plt.xlabel("Returns")
plt.ylabel("Frequency")
plt.title("Market Returns vs Strategy Returns")
plt.legend(["Cumulative Market Returns", "Cumulative Strategy Returns"])
plt.show()

"""The overall market performance has been mostly negative or close to neutral during the observed period. The market has been relatively more frequent in generating negative returns during this period.
##### The strategy's returns have been more varied, with some instances of strong positive performance. It shows a more diverse range of returns compared to the market, with some periods of strong positive performance.  We will also look st some risk-adjusted performance metrics.

Scatter plot and correlation between Market Returns and Strategy Returns:
"""

plt.scatter(returns_dataset["Cumulative Market Returns"], returns_dataset["Cumulative Strategy Returns"])
plt.xlabel("Market Returns")
plt.ylabel("Strategy Returns")
plt.title("Scatter Plot: Market Returns vs Strategy Returns")
plt.show()

correlation = returns_dataset.corr()
print("Correlation matrix:\n", correlation)

import numpy as np

def sharpe_ratio(returns, risk_free_rate=0.0):
    excess_returns = returns - risk_free_rate
    return np.mean(excess_returns) / np.std(excess_returns)

def sortino_ratio(returns, risk_free_rate=0.0, target_return=0.0):
    excess_returns = returns - risk_free_rate
    downside_returns = excess_returns.copy()
    downside_returns[excess_returns > target_return] = 0.0
    return np.mean(excess_returns) / np.std(downside_returns)

def calmar_ratio(returns, max_drawdown):
    return np.mean(returns) / max_drawdown

# Calculate risk-adjusted performance metrics
risk_free_rate = 0.0
market_returns = trade_dataset['Tomorrows Returns']
strategy_returns = trade_dataset['Strategy Returns']

sharpe_market = sharpe_ratio(market_returns, risk_free_rate)
sharpe_strategy = sharpe_ratio(strategy_returns, risk_free_rate)

sortino_market = sortino_ratio(market_returns, risk_free_rate)
sortino_strategy = sortino_ratio(strategy_returns, risk_free_rate)

# Calculate the maximum drawdown for the market and the strategy
cumulative_market_returns = trade_dataset['Cumulative Market Returns']
cumulative_strategy_returns = trade_dataset['Cumulative Strategy Returns']

max_dd_market = np.max(np.maximum.accumulate(cumulative_market_returns) - cumulative_market_returns)
max_dd_strategy = np.max(np.maximum.accumulate(cumulative_strategy_returns) - cumulative_strategy_returns)

calmar_market = calmar_ratio(market_returns, max_dd_market)
calmar_strategy = calmar_ratio(strategy_returns, max_dd_strategy)

print(f"Sharpe Ratio: Market = {sharpe_market:.3f}, Strategy = {sharpe_strategy:.3f}")
print(f"Sortino Ratio: Market = {sortino_market:.3f}, Strategy = {sortino_strategy:.3f}")
print(f"Calmar Ratio: Market = {calmar_market:.3f}, Strategy = {calmar_strategy:.3f}")

"""Comparison - This is including all the features"""

comparison_dataset = comparison_dataset.dropna()
plt.figure(figsize=(10,5))
plt.plot(comparison_dataset['Cumulative Market Returns'], color='r', label='Market Returns')
plt.plot(comparison_dataset['SVM'], color='b', label='Support Vector Machine')
plt.plot(comparison_dataset['Linear SVC'], color='y', label='Linear SVC')
plt.plot(comparison_dataset['Random Forest'], color='m', label='Random Forest')
plt.plot(comparison_dataset['Extra Tree Classifier'], color='k', label='Extra Tree Classifier')
plt.plot(comparison_dataset['Bagging with KNN'], color='c', label='Bagging with KNN')
plt.plot(comparison_dataset['Gradient Boosting'], color='g', label='Gradient Boosting')
plt.legend()
plt.show()